export const indexCollection = [
  {
    INDEX_ID: "204",
    COLUMN: "type_id",
    TYPE: "FOREIGN_TABLE",
    LABEL: "Type de document",
    SHORT_LABEL: "Type de document",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: true,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: true,
    VALEURS: {
      2: "Accident du Travail",
      9: "Congés",
      13: "Contrats",
      12: "Correspondance",
      16: "Demande de contrat",
      8: "Discipline",
      3: "Embauche",
      6: "Etat Civil",
      14: "Fin de contrat",
      4: "Formation",
      5: "Maladie",
      10: "Mutuelle",
      15: "Paye",
      11: "Retraite",
      7: "Sécurité sociale",
    },
    ORDER: true,
    ORDER_WAY: "asc",
    TABLENAME: "FT_14_2",
    FOREIGN_TABLE_ID: "101",
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: true,
    IS_FLOAT: false,
    IS_NUMERIC: true,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
    SONS: [{ COLUMN: "custom_n1", LABEL: "Document", TYPE: "DOCUMENT_TYPE" }],
  },
  {
    INDEX_ID: "205",
    COLUMN: "custom_n1",
    TYPE: "DOCUMENT_TYPE",
    LABEL: "Document",
    SHORT_LABEL: "Document",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: true,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: true,
    VALEURS: {
      23: "Acte de naissance",
      43: "Affiliation à la caisse de prévoyance",
      42: "Affiliation \u00e0 la caisse de retraite",
      115: "Aide \u00e0 l'embauche",
      121: "Archives",
      58: "Attestation ASSEDIC",
      50: "Attestation d'aptitude médicale",
      1: "Attestation d'aptitude médicale AT",
      12: "Attestation d'aptitude médicale MALADIE",
      60: "Attestation de logement",
      2: "Attestation de salaire AT",
      13: "Attestation de salaire MALADIE",
      119: "Attestation fiscale",
      84: "Attestations",
      65: "Avance sur salaire",
      25: "Avenant au contrat de travail",
      3: "Avis d'arrêt de travail AT",
      14: "Avis d'arrêt de travail MALADIE",
      113: "Bulletin de salaire",
      26: "Carte d'identification professionnelle",
      51: "Carte de sécurite sociale",
      52: "Carte de séjour",
      24: "Carte Nationale d'Identite/Passeport",
      122: "CDD",
      123: "CDI",
      62: "Certificat de travail",
      106: "Certificat médical",
      4: "Certificat médical AT",
      16: "Certificat médical MALADIE",
      27: "Compte Epargne Temps",
      28: "Contrat de Travail",
      107: "Correspondance CPAM",
      10: "Correspondance Entrante AT",
      101: "Correspondance Entrante caisse de congés payés",
      21: "Correspondance Entrante MALADIE",
      11: "Correspondance Sortante AT",
      102: "Correspondance Sortante caisse de congés payés",
      22: "Correspondance Sortante MALADIE",
      31: "CV",
      5: "Déclaration AT",
      9: "Décompte IJSS AT",
      19: "Décompte IJSS MALADIE",
      6: "Décompte Mutuelle AT",
      18: "Décompte Mutuelle MALADIE",
      69: "Demande d'absence",
      47: "Demande d'immatriculation CPAM",
      104: "Demande de congés",
      32: "Diplômes",
      73: "Divers",
      116: "Divers",
      117: "Divers",
      55: "Document préfecture",
      120: "DPAE",
      110: "Entreprise -> Salarié",
      49: "Etat Invalidité Incapacité",
      7: "Etat Invalidité Incapacité AT",
      20: "Etat Invalidité Incapacité MALADIE",
      75: "Fiche d'évaluation",
      36: "Fiche d'entretien d'embauche",
      35: "Fiche de renseignements",
      96: "Formation aux premiers secours",
      56: "Notification de sanctions disciplinaires",
      118: "Passeport",
      78: "Permis de Conduire B",
      79: "Permis de Conduire C",
      41: "Promesse d'embauche",
      57: "Réponse du salarié à une sanction disciplinaire",
      40: "Règlement intérieur",
      77: "Recyclage de formation",
      39: "RIB",
      66: "Saisie sur salaire",
      108: "Salarié -> Entreprise",
      63: "Solde de tout compte",
    },
    ORDER: false,
    TABLENAME: "FT_14_1",
    FOREIGN_TABLE_ID: "100",
    DEPENDENCY: "type_id",
    DEPENDENCY_KEY: "type_id",
    VALEURS_PARENTEES: {
      2: {
        Nom_Groupe: "Accident du Travail",
        Membres_Groupe: {
          1: "Attestation d'aptitude médicale AT",
          2: "Attestation de salaire AT",
          3: "Avis d'arrêt de travail AT",
          4: "Certificat médical AT",
          5: "Déclaration AT",
          6: "Décompte Mutuelle AT",
          7: "Etat Invalidité Incapacité AT",
          9: "Décompte IJSS AT",
          10: "Correspondance Entrante AT",
          11: "Correspondance Sortante AT",
        },
      },
      9: {
        Nom_Groupe: "Congés",
        Membres_Groupe: {
          69: "Demande d'absence",
          101: "Correspondance Entrante caisse de congés payés",
          102: "Correspondance Sortante caisse de congés payés",
          104: "Demande de congés",
        },
      },
      13: {
        Nom_Groupe: "Contrats",
        Membres_Groupe: {
          25: "Avenant au contrat de travail",
          28: "Contrat de Travail",
          121: "Archives",
        },
      },
      12: {
        Nom_Groupe: "Correspondance",
        Membres_Groupe: {
          108: "Salarié -> Entreprise",
          110: "Entreprise -> Salarié",
        },
      },
      16: {
        Nom_Groupe: "Demande de contrat",
        Membres_Groupe: { 122: "CDD", 123: "CDI" },
      },
      8: {
        Nom_Groupe: "Discipline",
        Membres_Groupe: {
          56: "Notification de sanctions disciplinaires",
          57: "Réponse du salarié à une sanction disciplinaire",
        },
      },
      3: {
        Nom_Groupe: "Embauche",
        Membres_Groupe: {
          31: "CV",
          35: "Fiche de renseignements",
          36: "Fiche d'entretien d'embauche",
          39: "RIB",
          40: "Règlement intérieur",
          41: "Promesse d'embauche",
          49: "Etat Invalidité Incapacité",
          50: "Attestation d'aptitude médicale",
          58: "Attestation ASSEDIC",
          60: "Attestation de logement",
          62: "Certificat de travail",
          75: "Fiche d'évaluation",
          106: "Certificat médical",
          115: "Aide \u00e0 l'embauche",
          120: "DPAE",
        },
      },
      6: {
        Nom_Groupe: "Etat Civil",
        Membres_Groupe: {
          23: "Acte de naissance",
          24: "Carte Nationale d'Identite/Passeport",
          26: "Carte d'identification professionnelle",
          51: "Carte de sécurite sociale",
          52: "Carte de séjour",
          55: "Document préfecture",
          78: "Permis de Conduire B",
          79: "Permis de Conduire C",
          118: "Passeport",
        },
      },
      14: {
        Nom_Groupe: "Fin de contrat",
        Membres_Groupe: { 63: "Solde de tout compte" },
      },
      4: {
        Nom_Groupe: "Formation",
        Membres_Groupe: {
          32: "Diplômes",
          73: "Divers",
          77: "Recyclage de formation",
          84: "Attestations",
          96: "Formation aux premiers secours",
        },
      },
      5: {
        Nom_Groupe: "Maladie",
        Membres_Groupe: {
          12: "Attestation d'aptitude médicale MALADIE",
          13: "Attestation de salaire MALADIE",
          14: "Avis d'arrêt de travail MALADIE",
          16: "Certificat médical MALADIE",
          18: "Décompte Mutuelle MALADIE",
          19: "Décompte IJSS MALADIE",
          20: "Etat Invalidité Incapacité MALADIE",
          21: "Correspondance Entrante MALADIE",
          22: "Correspondance Sortante MALADIE",
          116: "Divers",
        },
      },
      10: {
        Nom_Groupe: "Mutuelle",
        Membres_Groupe: {
          43: "Affiliation à la caisse de prévoyance",
          117: "Divers",
        },
      },
      15: {
        Nom_Groupe: "Paye",
        Membres_Groupe: {
          27: "Compte Epargne Temps",
          65: "Avance sur salaire",
          66: "Saisie sur salaire",
          113: "Bulletin de salaire",
          119: "Attestation fiscale",
        },
      },
      11: {
        Nom_Groupe: "Retraite",
        Membres_Groupe: { 42: "Affiliation \u00e0 la caisse de retraite" },
      },
      7: {
        Nom_Groupe: "Sécurité sociale",
        Membres_Groupe: {
          47: "Demande d'immatriculation CPAM",
          107: "Correspondance CPAM",
        },
      },
    },
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: true,
    IS_FLOAT: false,
    IS_NUMERIC: true,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "226",
    COLUMN: "custom_n4",
    TYPE: "FOREIGN_TABLE",
    LABEL: "Demande de contrat | Civilité",
    SHORT_LABEL: "Civilité",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: true,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: true,
    VALEURS: { 2: "Madame", 1: "Monsieur" },
    ORDER: true,
    ORDER_WAY: "asc",
    TABLENAME: "def_values_19",
    FOREIGN_TABLE_ID: "110",
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: true,
    IS_FLOAT: false,
    IS_NUMERIC: true,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "227",
    COLUMN: "custom_t1",
    TYPE: "TEXT",
    LABEL: "Demande de contrat | Prénom",
    SHORT_LABEL: "Prénom",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "228",
    COLUMN: "custom_t5",
    TYPE: "TEXT",
    LABEL: "Demande de contrat | Nom d'usage",
    SHORT_LABEL: "Nom d'usage",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "229",
    COLUMN: "custom_t6",
    TYPE: "TEXT",
    LABEL: "Demande de contrat | Nom Naissance",
    SHORT_LABEL: "Nom Naissance",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "230",
    COLUMN: "custom_t7",
    TYPE: "DATE",
    LABEL: "Demande de contrat | Date naissance",
    SHORT_LABEL: "Date naissance",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "231",
    COLUMN: "custom_t8",
    TYPE: "TEXT",
    LABEL: "Demande de contrat | N° de sécurité sociale",
    SHORT_LABEL: "N° de sécurité sociale",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "232",
    COLUMN: "custom_n5",
    TYPE: "INTEGER",
    LABEL: "Demande de contrat | Clé SS",
    SHORT_LABEL: "Clé SS",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: true,
    IS_FLOAT: false,
    IS_NUMERIC: true,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "233",
    COLUMN: "custom_t9",
    TYPE: "TEXT",
    LABEL: "Demande de contrat | Adresse",
    SHORT_LABEL: "Adresse",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "234",
    COLUMN: "custom_t10",
    TYPE: "TEXT",
    LABEL: "Demande de contrat | Complément d'adresse",
    SHORT_LABEL: "Complément d'adresse",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "235",
    COLUMN: "custom_t11",
    TYPE: "TEXT",
    LABEL: "Demande de contrat | CP",
    SHORT_LABEL: "CP",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "236",
    COLUMN: "custom_t12",
    TYPE: "TEXT",
    LABEL: "Demande de contrat | Ville",
    SHORT_LABEL: "Ville",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "243",
    COLUMN: "custom_d5",
    TYPE: "DATE",
    LABEL: "Demande de contrat | Date début contrat",
    SHORT_LABEL: "Date début contrat",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: true,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "238",
    COLUMN: "custom_t14",
    TYPE: "TEXT",
    LABEL: "Demande de contrat | Heure début",
    SHORT_LABEL: "Heure début",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "239",
    COLUMN: "custom_n6",
    TYPE: "FOREIGN_TABLE",
    LABEL: "Demande de contrat | Boutique",
    SHORT_LABEL: "Boutique",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: true,
    VALEURS: [],
    ORDER: true,
    ORDER_WAY: "asc",
    TABLENAME: "def_values_20",
    FOREIGN_TABLE_ID: "111",
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: true,
    IS_FLOAT: false,
    IS_NUMERIC: true,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "240",
    COLUMN: "custom_t15",
    TYPE: "TEXT",
    LABEL: "Demande de contrat | Nom personne absente",
    SHORT_LABEL: "Nom personne absente",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "241",
    COLUMN: "custom_n7",
    TYPE: "FOREIGN_TABLE",
    LABEL: "Demande de contrat | Motif absence",
    SHORT_LABEL: "Motif absence",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: true,
    VALEURS: {
      2: "Accident du Travail",
      9: "Congé",
      8: "Discipline",
      14: "Fin de contrat",
      4: "Formation",
      5: "Maladie",
    },
    ORDER: true,
    ORDER_WAY: "asc",
    TABLENAME: "def_values_21",
    FOREIGN_TABLE_ID: "112",
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: true,
    IS_FLOAT: false,
    IS_NUMERIC: true,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "242",
    COLUMN: "custom_d4",
    TYPE: "DATE",
    LABEL: "Demande de contrat | Date fin contrat",
    SHORT_LABEL: "Date fin contrat",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: true,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "244",
    COLUMN: "custom_f1",
    TYPE: "FLOAT",
    LABEL: "Demande de contrat | Volume hébdo",
    SHORT_LABEL: "Volume hébdo",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: true,
    IS_NUMERIC: true,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "245",
    COLUMN: "custom_f2",
    TYPE: "FLOAT",
    LABEL: "Demande de contrat | Lundi",
    SHORT_LABEL: "Lundi",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: true,
    IS_NUMERIC: true,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "246",
    COLUMN: "custom_f3",
    TYPE: "FLOAT",
    LABEL: "Demande de contrat | Mardi",
    SHORT_LABEL: "Mardi",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: true,
    IS_NUMERIC: true,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "247",
    COLUMN: "custom_f4",
    TYPE: "FLOAT",
    LABEL: "Demande de contrat | Mercredi",
    SHORT_LABEL: "Mercredi",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: true,
    IS_NUMERIC: true,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "248",
    COLUMN: "custom_f5",
    TYPE: "FLOAT",
    LABEL: "Demande de contrat | Jeudi",
    SHORT_LABEL: "Jeudi",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: true,
    IS_NUMERIC: true,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "249",
    COLUMN: "custom_f6",
    TYPE: "FLOAT",
    LABEL: "Demande de contrat | Vendredi",
    SHORT_LABEL: "Vendredi",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: true,
    IS_NUMERIC: true,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "250",
    COLUMN: "custom_f7",
    TYPE: "FLOAT",
    LABEL: "Demande de contrat | Samedi",
    SHORT_LABEL: "Samedi",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: true,
    IS_NUMERIC: true,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "251",
    COLUMN: "custom_f8",
    TYPE: "FLOAT",
    LABEL: "Demande de contrat | Dimanche",
    SHORT_LABEL: "Dimanche",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: true,
    IS_NUMERIC: true,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "252",
    COLUMN: "custom_d6",
    TYPE: "DATE",
    LABEL: "Demande de contrat | Date demande",
    SHORT_LABEL: "Date demande",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: true,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
  {
    INDEX_ID: "253",
    COLUMN: "custom_t13",
    TYPE: "EMAIL",
    LABEL: "Demande de contrat | Adresse Mail",
    SHORT_LABEL: "Adresse Mail",
    COLL_ID: "coll_14",
    AUTOCOMPLETE: false,
    SHOW_IN_RESULTLIST: true,
    MANDATORY: false,
    MULTIVALUED: false,
    EXCLU_LAD: false,
    FIXED_VALUES_TABLE: false,
    IS_EXTERNAL: false,
    IS_PREDEFINED_LIST: false,
    IS_DATE: false,
    IS_INT: false,
    IS_FLOAT: false,
    IS_NUMERIC: false,
    WIZARD: "",
    SORTABLE: true,
    STANDARDIZED_WIZARD: "",
    Color_Id: "0",
    Color_Code: "",
  },
];

export const user = {
  OverQuota_Mode: "1",
  User_Id: "70590a02a99e1c061eac0318af82a7ae",
  FirstName: "",
  LastName: "Admin 269",
  Mail: "admin_269@zeendoc.com",
  Department: "",
  Mail_Sur_Depot: null,
  Decipher_Key: "defc081c6658c857178cbd9b41ab63ce",
  MD5_Password: "$2y$10$GQiggeRQWji2ofiU2NBdu.nFFuicyptvLGH5PksL9RnBhTtSi8ZJa",
  Derniere_Connexion: "2006-01-01 00:00:00",
  Prefs: {
    lang: "fr",
    Nb_Par_Page: 20,
    N_Comments_Color: "1",
    Comments_Color: "FAF898",
    TimeZone: "Europe/Paris",
    coll_0_Result_Indexes: "|custom_t1|custom_t2|Commented|Page_Count|",
    coll_1_Result_Indexes:
      "|custom_n7|custom_n3|custom_t2|custom_t5|custom_t3|Commented|Page_Count|",
    coll_12_Result_Indexes:
      "|custom_n6|custom_t4|custom_t5|custom_d1|custom_t6|Commented|Page_Count|",
    coll_2_Result_Indexes: "|custom_n1|custom_n2|Commented|Page_Count|",
    coll_9_Result_Indexes:
      "|custom_t4|custom_t5|custom_d1|custom_t6|custom_n3|Commented|Page_Count|",
    _Result_Indexes:
      "|Res_Id|N_Status|Filesize|FilesizeOriginal|Comment|Stamp|N_Modele_LAD|Postit|signed|Statut_Signature|Format|folders|Linked_Docs|Shipment_Status|Is_Commented|Comment|Thumb|History|",
    coll_12_Hidden_Result_Indexes:
      "|custom_n3|custom_d2|custom_d3|custom_n4|custom_n1|custom_f1|custom_n5|custom_t8|custom_t1|custom_t2|custom_t3|custom_f2|custom_n2|custom_t7|custom_t9|Res_Id|Creation_Date|N_Status|PDF_Filesize|Original_Filesize|Comment|Stamp|Postit|Conversation|N_Modele_LAD|signed|Statut_Signature|Doublons|Doublons_Inactifs|Filename|Format|Upload_User_Id|signataires_oodrive|signataires_oodrive_signed|signataires_oodrive_waiting|signataires_oodrive_refused|folders|Shipment_Status|Posted|History|Thumb|Linked_Docs|Docs_Doublons|",
  },
  Locales_Prefs: { Upload_Form: "FLASH", Visualiseur_PDF: "ZDV" },
  Est_SuperAdmin: false,
  Last_Page:
    "/zeendoc/www/ZeenDoc_IHM_3_0/src/Ihm/Search/Formulaire_Saisie_Config_Set.php",
  Last_Access: "2022-07-25 11:03:54",
  User_Log_Info_Checked: true,
};
